spring:
  profiles:
    active: default,local
  application:
    name: oauth-v1
server:
  context-path: /uaa
  use-forward-headers: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
logging:
  level:
    PROTOCOL_MESSAGE: ERROR
    org:
      opensaml: ERROR
      springframework:
        web: ERROR
        security: ERROR
        saml: ERROR
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
gft:
  saml:
    idpMetadata: https://workspace-int.gft.com/idp/shibboleth
  oauth2:
    keystore:
      password: mySecretKey
server:
  port: 11003