spring:
  application:
    name: oauth-v1
server:
  port: 11001
  context-path: /uaa
  use-forward-headers: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/
logging:
  level:
    PROTOCOL_MESSAGE: ERROR
    org:
      opensaml: ERROR
      springframework:
        web: ERROR
        security: ERROR
        saml: ERROR
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
gft:
  saml:
    idpMetadata: https://workspace-int.gft.com/idp/shibboleth
  ldap:
    domain: gft.com
    url: ldap://dcher1.gft.com/
  oauth2:
    keystore:
      password: mySecretKey